# Generated by Django 3.2.8 on 2022-02-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
                ('order', models.SmallIntegerField(default=0, help_text='Higher shows first')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
                'ordering': ('-order',),
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('submit_by', models.DateTimeField(help_text='Time that things must be submitted by in UTC')),
            ],
            options={
                'ordering': ('date',),
                'default_related_name': 'races',
            },
        ),
        migrations.CreateModel(
            name='RaceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=64)),
                ('default_number', models.IntegerField(help_text="The driver's default number")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ('last_name',),
                'default_related_name': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='RaceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Race Team',
                'verbose_name_plural': 'Race Teams',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Twitter ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('profile_img', models.URLField()),
            ],
            options={
                'verbose_name': 'Twitter User',
                'verbose_name_plural': 'Twitter Users',
            },
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='picks.racedriver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='picks.race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='picks.raceteam')),
            ],
            options={
                'default_related_name': 'cars',
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='racedriver',
            name='default_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='picks.raceteam'),
        ),
        migrations.AddField(
            model_name='race',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='picks.schedule'),
        ),
        migrations.CreateModel(
            name='RacePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=64)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.raceentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.twitteruser')),
            ],
            options={
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
