# Generated by Django 4.0.2 on 2022-02-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_alter_schedule_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-year',)},
        ),
    ]
