# Generated by Django 3.2.8 on 2022-02-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_raceresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racepick',
            options={'default_related_name': 'picks', 'ordering': ('timestamp',), 'verbose_name': 'Race Pick', 'verbose_name_plural': 'Race Picks'},
        ),
        migrations.AlterModelOptions(
            name='raceresult',
            options={'default_related_name': 'results', 'ordering': ('race', 'position'), 'verbose_name': 'Race Result', 'verbose_name_plural': 'Race Results'},
        ),
        migrations.AlterField(
            model_name='racepick',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picks', to='picks.racedriver'),
        ),
        migrations.AlterField(
            model_name='racepick',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='picks.race'),
        ),
        migrations.AlterField(
            model_name='racepick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='picks.twitteruser'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='picks.racedriver'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='picks.race'),
        ),
    ]
