# Generated by Django 4.0.2 on 2022-02-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('year',)},
        ),
    ]
