# Generated by Django 4.0.2 on 2022-02-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0006_alter_race_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'default_related_name': 'races', 'ordering': ('date',)},
        ),
    ]
