# Generated by Django 4.0.2 on 2022-02-12 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0007_alter_race_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='submit_by',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time that things must be submitted by in UTC'),
            preserve_default=False,
        ),
    ]
