# Generated by Django 3.2.8 on 2022-02-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0008_race_submit_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Twitter ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
