# Generated by Django 3.2.8 on 2022-02-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0009_twitteruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitteruser',
            options={'verbose_name': 'Twitter User', 'verbose_name_plural': 'Twitter Users'},
        ),
    ]
