# Generated by Django 3.2.8 on 2022-02-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0010_alter_twitteruser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='profile_img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
