# Generated by Django 3.2.8 on 2022-02-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0011_twitteruser_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
                ('order', models.SmallIntegerField(default=0, help_text='Higher shows first')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
                'ordering': ('-order',),
            },
        ),
        migrations.CreateModel(
            name='RacePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.twitteruser')),
            ],
            options={
                'unique_together': {('race', 'user')},
            },
        ),
    ]
